services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: false

  Shopware\WebInstaller\:
    resource: '../../*'
    exclude: '../../{Command,Controller,Resources,Tests}'

  Shopware\WebInstaller\Controller\:
    resource: '../../Controller'
    public: true
    tags: ['controller.service_arguments']
